"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";
import NavbarPublic from "./ui/navbar/NavbarPublic";
import { usePathname } from "next/navigation";
import NavbarHome from "./ui/navbar/NavbarHome";
import { Container } from "@chakra-ui/react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const getNavbar = () => {
    if (pathname === "/") {
      return <NavbarPublic />;
    } else if (pathname === "/home") {
      return <NavbarHome />;
    }
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container maxW="7xl">
            {getNavbar()}
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
